### ISSUE TITLE
Move the testdata out of the release

### ISSUE THREAD

**Issue by lboogaard** [interferopy/interferopy#38]
The test data in `./example/data/` is quite heavy (the cubes are ~23Mb each, total is 96 Mb). I think it make sense to not ship these with Interferopy automatically (the zipped release is now 80Mb, which is mainly the test data).

My suggestion would be to keep the data, but have it outside of the released distribution (that is also on PyPi). Perhaps we can have a function somewhere (`examples.download_pisco()` ?) to download the data for those that want to use it.

I'm not sure what the best way to do this is, but I think it might be a `release` branch that does not include the example data? I'm open to better suggestions.

**Comment by rameyer** [comment]
Perhaps the simplest way is to upload manually the zipped files of choice (e.g. leaving out the test data) for the releases. Will this therefore propagate for the 'pip install interferopy' ?

**Comment by rameyer** [comment]
OK @lboogaard my proposed solution is to remove the examples folder from the zip files that will be distributed by the 1.0.1 version (here and on ZENODO). I think we need to keep these examples and data on github if people want to test stuff. It's an easy fix, although it has to be repeated every time we do a release. But for now I think it is still worth it - I don't want to invest too much time on this.

**Comment by lboogaard** [comment]
Agreed.

**Comment by rameyer** [comment]
Done - the 1.0.1 release contains a light zip file as well as the full github repo content.
